Social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogout.as_view(), name='user_logout'),

    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('profile/update/<int:user_id>', views.UserUpdateProfile.as_view(), name='user_update'),

    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnFollowView.as_view(), name='user_unfollow'),

    path('users/', views.UsersView.as_view(), name='user_all'),
]

home/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('post/<int:post_id>/', DetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>', PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>', PostUpdateView.as_view(), name='post_update'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('replay/<int:post_id>/<int:comment_id>/', PostAddReplyView.as_view(), name='add_replay'),
    path('like/<int:post_id>/', PostLikeView.as_view(), name='post_like'),

    path('explore/', ExploreView.as_view(), name='post-explore')
]

home/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

UserModel = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.body}'

    def get_absolute_url(self):
        return reverse('home:post_detail', args=(self.id, ))

    def likes_count(self):
        return self.pvote.count()

    def user_can_like(self, user):
        user_like = user.uvote.filter(post=self)
        if user_like:
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    replay = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_replay = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body} - {self.post}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvote')

    def __str__(self):
        return f'{self.user} liked {self.post.slug}'

home/forms.py
from django import forms

from home.models import Post, Comment


class UpdateAndCreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', })
        }
        labels = {
            'body': 'متن کامنت'
        }


class CommentReplaysForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        widgets = {
            'body': forms.TextInput(attrs={'class': 'form-control', })
        }
        labels = {
            'body': 'متن کامنت'
        }


class SearchForm(forms.Form):
    search = forms.CharField(label='جستجو کنید', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'اینجا سرچ کن'}))

home/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.text import slugify
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from account.models import Relation
from home.forms import UpdateAndCreatePostForm, CommentCreateForm, CommentReplaysForm, SearchForm
from home.models import Post, Comment, Vote
from django.contrib import messages


class HomeView(View):
    form_class = SearchForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
        return render(request, 'home/home.html', {'posts': posts, 'form': self.form_class})


class DetailView(View):
    template_name = 'home/detail.html'
    form_class_comment = CommentCreateForm
    form_class_replays = CommentReplaysForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, post_id):
        user_can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            user_can_like = True
        form = self.form_class_comment
        reply_form = self.form_class_replays
        comments = self.post_instance.pcomments.filter(is_replay=False)
        return render(request, self.template_name,
                      {'post': self.post_instance, 'comments': comments, 'form': form, 'reply_form': reply_form,
                       'user_can_like': user_can_like})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class_comment(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'کامنت شما با موفقیت ارسال شد', 'success')
            return redirect('home:post_detail', self.post_instance.id)
        else:
            messages.error('request', 'کامنت شما ارسال نشد لطفا دوباره تلاش کنید', 'danger')
            return redirect('home:post_detail', self.post_instance.id)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'پست با موفقبت پاک شد', 'success')
        else:
            messages.error(request, 'شما نمیتواند پست را پاک کنید', 'error')
        return redirect('home:home')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = UpdateAndCreatePostForm
    template_name = 'home/update.html'

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if not self.post_instance.user.id == request.user.id:
            messages.error(request, 'شما نمیتوانید این پست را اپدیت کنید', 'error')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.post_instance)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.post_instance)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'با موفقیت اپدیت  شد', 'success')
            return redirect('home:post_detail', self.post_instance.id)


class PostCreateView(LoginRequiredMixin, View):
    form_class = UpdateAndCreatePostForm
    template_name = 'home/create.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'پست با موفقیت ارسال شد', 'success')
            return redirect('home:post_detail', new_post.id)
        messages.error(request, 'شما نمیتوانید پست اضافه کنید')


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplaysForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST or None)
        if form.is_valid():
            replay = form.save(commit=False)
            replay.user = request.user
            replay.post = post
            replay.replay = comment
            replay.is_replay = True
            replay.save()
            messages.success(request, 'کامنت شما ارسال شد', 'success')
        else:
            messages.error(request, 'کامنت ارسال نشد دوباره تلاش کنید', '')

        return redirect('home:post_detail', post.id)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post)
        if like.exists():
            messages.error(request, 'شما قبلا این پست را لایک کرده اید', 'danger')
        else:
            Vote.objects.create(user=request.user, post=post)
            messages.success(request, 'پست با موفقیت لایک شد', 'success')

        return redirect('home:post_detail', post.id)


class ExploreView(LoginRequiredMixin, View):

    def get(self, request):
        followers = list(Relation.objects.filter(from_user=request.user).values_list('to_user', flat=True))
        posts = Post.objects.filter(user__in=followers)

        return render(request, 'home/explore.html', {'posts': posts})

home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" novalidate>
    {{ form.as_p }}
        {% csrf_token %}
    <button class="btn btn-success" type="submit"> تایید </button>
    </form>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="post">
        <div class="post__avatar">
            <img src="https://ps.w.org/simple-user-avatar/assets/icon-256x256.png?rev=2413146" alt="">
        </div>

        <div class="post__body">
            <div class="post__header">
                <div class="post__headerText">
                    <h3>
                        {{ post.username }}
                        <span class="post__headerSpecial"><span
                                class="material-icons post__badge">  </span><a
                                href="{% url 'account:user_profile' post.user.id %}">@{{ post.user.username }}</a></span>
                    </h3>
                </div>
                <div class="post__headerDescription">
                    <p>{{ post.body }}</p>
                </div>
                <span class="material-icons">{{ post.created|date:"Y M" }}</span>

            </div>

            <div class="post__footer">
                {% if request.user.id == post.user.id %}
                    <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger text-light"> حذف </a>
                    <a href="{% url 'home:post_update' post.id %}" class="btn btn-info text-light"> اپدیت </a>
                {% endif %}
                {% if request.user.is_authenticated %}

                    <a href="{% url 'home:post_like' post.id %}"
                       class="  btn btn-primary text-light" {% if user_can_like %} disabled {% endif %}>
                        لایک{{ post.likes_count }} </a>


                {% endif %}
            </div>
            <hr>


        </div>

    </div>

    <div id="comments" class="comments-area">
        <h2 class="comments-title">
            نظرات <span class="comment-count">{{ comments.count }}</span>
        </h2>
        <div class="comment-list-wrap">
            {% if request.user.is_authenticated %}
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button class="btn btn-info" type="submit"> ارسال نظر</button>
                </form>
            {% else %}
                <p class="alert alert-danger"> فقط کاربرانی که لاگین کردن میتونن کامنت بزارن </p>
            {% endif %}
            <ol class="comment-list">
                {% for comment in comments %}
                    <div class="card bg-dark text-white">
                        <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
                        <p class="card-body">{{ comment.body }}</p>

                        {% if request.user.is_authenticated %}
                            <form action="{% url 'home:add_replay' post.id comment.id %}" method="post">
                                {% csrf_token %}
                                {{ reply_form.as_p }}
                                <input type="submit" value="send">
                            </form>
                        {% endif %}

                        {% with replays=comment.rcomment.all %}
                            {% for reply in replays %}
                                <p class="bg-primary p-3 m-2">{{ reply.user }} <br/> {{ reply.body }}</p>
                            {% endfor %}
                        {% endwith %}

                    </div><br/>
                {% empty %}
                    <p>هیچ کامنتی ارسال نشده</p>
                {% endfor %}
        </div>
    </div>


    <!-- post ends -->
{% endblock %}

home/templates/home/explore.html
{% extends 'base.html' %}

{% block content %}


    {% for post in posts %}

        <div class="post">
            <div class="post__avatar">
                <img src="https://ps.w.org/simple-user-avatar/assets/icon-256x256.png?rev=2413146" alt="">
            </div>

            <div class="post__body">
                <div class="post__header">
                    <div class="post__headerText">
                        <h3>
                            {{ post.user.username }}
                            <span class="post__headerSpecial"><span
                                    class="material-icons post__badge">  </span>@{{ post.user.username }}</span>
                        </h3>
                    </div>
                    <div class="post__headerDescription">
                        <a href="{{ post.get_absolute_url }}">
                            <p>{{ post.body|truncatewords:50 }}</p>
                        </a>
                    </div>
                </div>

                <div class="post__footer">
                    <span class="material-icons"> لایک می </span>
                </div>
            </div>
        </div>
        <!-- post ends -->

    {% endfor %}

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block content %}

    <div class="feed__header">
        <h2>خانه</h2>
    </div>


    <form method="get">

        <div class="tweetbox__input">
            {{ form.as_p }}
        </div>
        <button type="submit" class="tweetBox__tweetButton">جستجو</button>

    </form>
    <hr>

    {% for post in posts %}

        <div class="post">
            <div class="post__avatar">
                <img src="https://ps.w.org/simple-user-avatar/assets/icon-256x256.png?rev=2413146" alt="">
            </div>

            <div class="post__body">
                <div class="post__header">
                    <div class="post__headerText">
                        <h3>
                            {{ post.user.username }}
                            <span class="post__headerSpecial"><span
                                    class="material-icons post__badge">  </span>@{{ post.user.username }}</span>
                        </h3>
                    </div>
                    <div class="post__headerDescription">
                        <a href="{{ post.get_absolute_url }}">
                            <p>{{ post.body|truncatewords:50 }}</p>
                        </a>
                    </div>
                </div>


            </div>
        </div>
        <!-- post ends -->

    {% endfor %}
    </div>

{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" novalidate>
    {{ form.as_p }}
        {% csrf_token %}
    <button type="submit"> تایید و اپدیت </button>
    </form>

{% endblock %}